// Extra portal screens: Google sign-in, teams, account, charts, merge, trainer/student tools, admin settings.
const chartsHtml = cs => !cs || !cs.length ? '<p class="empty">Not enough data yet.</p>' : `<div class="grid">${cs.map(c => { const max = Math.max(...c.values, 1), n = c.values.length, w = Math.max(280, n * 44), bar = w / n;
  return `<article class="card"><h3>${esc(c.title)}</h3><div class="scroll"><svg viewBox="0 0 ${w} 170" width="${w}" height="170" role="img" aria-label="${esc(c.title)}">${c.values.map((v, i) => { const h = Math.round(110 * v / max); return `<rect x="${i * bar + 6}" y="${130 - h}" width="${bar - 12}" height="${h}" fill="#1565c0" rx="3"/><text x="${i * bar + bar / 2}" y="${124 - h}" font-size="11" text-anchor="middle" fill="currentColor">${v}</text><text x="${i * bar + bar / 2}" y="148" font-size="10" text-anchor="middle" fill="currentColor">${esc(String(c.labels[i]).slice(0, 9))}</text>`; }).join('')}</svg></div></article>`; }).join('')}</div>`;
const spin = f => async e => { const b = e.target; b.disabled = true; try { await f(b); } finally { b.disabled = false; } };
const roleLabel = r => ({owner: 'Owner', admin: 'Company Admin', procurement: 'Procurement Manager', sales: 'Sales Manager', hr: 'HR Manager', engineering: 'Engineering Manager', viewer: 'Viewer'}[r] || r);
const TEAM_ROLES = ['admin','procurement','sales','hr','engineering','viewer'];
const waBtn = (txt, msg) => `<a class="btn ghost sm" target="_blank" rel="noopener" href="${IA.wa(msg)}">${txt}</a>`;

// ---- Google sign-in (official Google Identity Services; token verified server-side) ----
for (const k of ['login', 'register']) { const o = views[k]; views[k] = () => o() + '<div id="gbtn" style="margin-top:14px"></div><p class="meta">Google sign-in is optional. We never see your Google password.</p>'; }
async function mountGoogle() {
  const el = $('#gbtn'); if (!el) return; const s = await pub('settings'); const id = s.ok && s.data.google_client_id; if (!id) { el.innerHTML = ''; return; }
  await loadScript('https://accounts.google.com/gsi/client'); google.accounts.id.initialize({client_id: id, callback: async x => { const r = await call('google_login', {credential: x.credential, role: (document.querySelector('[name=role]') || {}).value}); if (!r.ok) return alert(r.error); me = r.user; location.hash = '#/dashboard'; route(); }});
  google.accounts.id.renderButton(el, {theme: 'outline', size: 'large', text: 'continue_with', width: 280});
}
const _wire = wire; wire = function () { _wire(); mountGoogle(); };

// ---- nav additions by role ----
const _nav = nav; nav = function () { _nav(); if (!me) return; const p = $('#pnav'), rs = me.roles || [me.role], r = me.company_role, add = [];
  add.push('<a href="#/learning">My learning</a>', '<a href="#/analytics">Analytics</a>');
  if (me.company_id || ['supplier','mro','company_rep','company_admin','trainer','employer'].some(x => rs.includes(x))) add.push('<a href="#/team">Team</a>');
  if (['owner','sales'].includes(r)) add.push('<a href="#/leads">Leads</a>'); if (['owner','hr'].includes(r) || rs.includes('employer')) add.push('<a href="#/jobs-manage">Jobs</a>');
  if (rs.includes('trainer')) add.push('<a href="#/earnings">Earnings</a>'); add.push('<a href="#/account">Account</a>'); p.innerHTML += add.join(''); };
if (location.hash.startsWith('#/accept/')) sessionStorage.setItem('ia_invite', location.hash.split('/')[2]);

// ---- dashboard: charts + pending invite ----
const _dash = views.dashboard; views.dashboard = async () => { const h = await _dash(), a = await call('analytics'), inv = sessionStorage.getItem('ia_invite');
  return (inv ? `<p class="card ai">You have a company invitation. <button class="btn primary sm" id="acceptInv">Accept invitation</button></p>` : '') + h + '<h3>Analytics</h3>' + chartsHtml(a.charts) + `<p>${waBtn('WhatsApp support', 'Hello Indian Aeronautics Support, I need help with my dashboard.')}</p>`; };
views.analytics = async () => { const a = await call('analytics'); return '<h2>Analytics</h2><p class="meta">Built from your real activity. Empty charts mean there is no data yet.</p>' + chartsHtml(a.charts); };
views.accept = async p => { sessionStorage.setItem('ia_invite', p[0]); return '<h2>Company invitation</h2><p>Log in with the invited email address, then accept from your dashboard.</p><a class="btn primary" href="#/dashboard">Continue</a>'; };

// ---- account ----
views.account = async () => { const r = await call('me'), u = r.user, d = await call('my_data');
  return `<h2>Account</h2><p class="meta">${esc(u.email)} · roles: ${esc((u.roles || []).join(', '))}${u.google ? ' · Google linked' : ''}</p>
  ${form('profile_save', fld('name', 'Name', {v: u.name, req: 1}) + fld('phone', 'Phone') + '<label><input type="checkbox" name="marketing" style="width:auto"> I want marketing emails (transactional emails are always sent)</label>', 'Save profile')}
  <h3>Add another role</h3>${form('roles_add', fld('role', 'Role', {opts: [['buyer','Buyer'],['supplier','Supplier'],['professional','Aerospace professional'],['trainer','Trainer'],['student','Student'],['mro','MRO provider'],['employer','Employer'],['company_rep','Company representative']]}), 'Add role')}
  <h3>Your data</h3><p class="meta">${d.ok ? `RFQs: ${d.rfqs} · conversations: ${d.messages}` : ''}</p>
  ${u.google ? '<button class="btn ghost sm" id="gdisc">Disconnect Google</button> ' : ''}<button class="btn ghost sm" id="delReq">Request account deletion</button> ${waBtn('Contact support', 'Hello Indian Aeronautics Support, I need help with my account.')}`; };

// ---- team ----
views.team = async () => { const r = await call('team_list'); if (!r.ok) return `<h2>Company team</h2><p class="empty">${esc(r.error)} Create or claim a company first.</p>`; const mgr = ['owner', 'admin'].includes(me.company_role);
  return `<h2>Company team</h2><p class="meta">Your role: ${esc(roleLabel(me.company_role))}. Each role only sees what it needs (HR cannot see procurement files; Procurement cannot see candidates).</p>
  ${table(['Name', 'Role', ''], r.data.map(m => `<tr><td>${esc(m.name)}</td><td>${mgr && m.role !== 'owner' ? `<select data-trole="${m.id}">${TEAM_ROLES.map(x => `<option value="${x}" ${x === m.role ? 'selected' : ''}>${roleLabel(x)}</option>`).join('')}</select>` : esc(roleLabel(m.role))}</td><td>${mgr && m.role !== 'owner' ? `<button class="btn ghost sm" data-trem="${m.id}">Remove</button>` : ''}</td></tr>`))}
  ${mgr ? `<h3>Invite team member</h3>${form('team_invite', fld('name', 'Name') + fld('email', 'Email', {t: 'email', req: 1}) + fld('role', 'Role', {opts: TEAM_ROLES.map(x => [x, roleLabel(x)])}), 'Send invitation')}
  <h3>Pending invitations</h3>${table(['Email', 'Role', ''], r.invites.map(i => `<tr><td>${esc(i.email)}</td><td>${esc(roleLabel(i.role))}</td><td><button class="btn ghost sm" data-icancel="${i.id}">Cancel</button></td></tr>`))}` : ''}`; };

// ---- leads, jobs ----
views.leads = async () => { const r = await call('leads_list'); if (!r.ok) return `<p class="msg err">${esc(r.error)}</p>`; const S = ['New','Contacted','Qualified','Quotation','Negotiation','Won','Lost'];
  return `<h2>Leads</h2>${table(['Date', 'Buyer', 'Requirement', 'Status', 'Est. value', 'Follow-up', 'Notes'], r.data.map(l => `<tr><td>${date(l.created)}</td><td>${esc(l.buyer_name)}<br><span class="meta">${esc(l.buyer_email)} ${esc(l.buyer_phone)}</span></td><td>${esc(l.requirement)}</td><td><select data-lead="${l.id}" data-f="status">${S.map(s => `<option ${s === l.status ? 'selected' : ''}>${s}</option>`).join('')}</select></td><td><input data-lead="${l.id}" data-f="est_value" value="${esc(l.est_value)}" size="8"></td><td><input type="date" data-lead="${l.id}" data-f="follow_up" value="${esc(String(l.follow_up).slice(0, 10))}"></td><td><input data-lead="${l.id}" data-f="notes" value="${esc(l.notes)}"></td></tr>`))}`; };
views['jobs-manage'] = async () => { const r = await call('jobs_mine');
  return `<h2>Jobs</h2>${r.ok ? table(['Title', 'Status', 'Applications', ''], r.data.map(j => `<tr><td>${esc(j.title)}</td><td>${esc(j.status)}</td><td>${j.applications}</td><td><a href="#/applications/${j.id}">View</a></td></tr>`)) : `<p class="empty">${esc(r.error)}</p>`}<h3>Post a job (reviewed before it goes live)</h3>${form('job_post', fld('title', 'Title', {req: 1}) + fld('city', 'City') + fld('type', 'Type', {opts: ['Full-time', 'Contract', 'Internship']}) + fld('description', 'Description', {area: 1}) + fld('apply_email', 'Applications email', {t: 'email', req: 1}), 'Submit job')}`; };
views.applications = async p => { const r = await call('applications', {job_id: p[0]}); if (!r.ok) return `<p class="msg err">${esc(r.error)}</p>`;
  return `<h2>Applications</h2><p class="meta">Candidate email addresses are not shown; message candidates through the platform.</p>${table(['Date', 'Candidate', 'Message', 'Status', ''], r.data.map(a => `<tr><td>${date(a.created)}</td><td>${esc(a.name)}</td><td>${esc(a.message)}</td><td><select data-app="${a.id}">${['Received','Shortlisted','Rejected','Hired'].map(s => `<option ${s === a.status ? 'selected' : ''}>${s}</option>`).join('')}</select></td><td><a href="#/chat/${a.user_id}">Message</a></td></tr>`))}`; };

// ---- academy: student, trainer ----
views.learning = async () => { const r = await call('my_courses');
  return `<h2>My learning</h2>${table(['Course', 'Trainer', 'Status', 'Progress', 'Certificate', ''], (r.data || []).map(c => `<tr><td>${esc(c.title)}</td><td>${esc(c.trainer_name)}</td><td>${esc(c.status)}</td><td><div class="bar"><i style="width:${c.progress}%"></i></div>${c.progress}%</td><td>${c.certificate ? 'Issued — contact your trainer for the file' : '—'}</td><td>${c.status === 'Active' ? `<a href="#/classroom/${c.course_id}">Classroom</a> · ` : ''}<a href="#/chat/${c.trainer_id}">Message trainer</a></td></tr>`))}<p class="meta">Assignments are not available yet. <a href="#/academy">Browse courses</a></p>`; };
views.classroom = async p => { const r = await call('discussion_list', {course_id: p[0]}); if (!r.ok) return `<p class="msg err">${esc(r.error)}</p>`; const trainer = (me.roles || []).includes('trainer');
  return `<h2>${esc(r.course)} — discussion</h2><p class="meta">Other students' contact details are never shown here.</p><div class="chat">${r.data.map(d => `<div class="b"><strong>${esc(d.name)}</strong> <span class="badge">${esc(d.kind)}</span><br>${esc(d.body)}<div class="meta">${new Date(d.created).toLocaleString('en-IN')}</div></div>`).join('') || '<p class="empty">No posts yet.</p>'}</div>${form('discussion_post', `<input type="hidden" name="course_id" value="${esc(p[0])}">` + (trainer ? fld('kind', 'Type', {opts: [['announcement', 'Announcement'], ['reply', 'Reply']]}) : '') + fld('body', 'Message', {area: 1, req: 1}), 'Post')}`; };
views.students = async () => { const r = await call('course_students');
  return `<h2>Students</h2>${table(['Course', 'Student', 'Status', 'Paid', 'Progress %', 'Certificate', ''], (r.data || []).map(s => `<tr><td>${esc(s.course)}</td><td>${esc(s.student)}</td><td>${esc(s.status)}</td><td>${s.paid ? 'Yes' : 'No'}</td><td><input type="number" min="0" max="100" value="${s.progress}" data-prog="${s.id}" style="width:80px"></td><td><input type="checkbox" data-cert="${s.id}" ${s.certificate ? 'checked' : ''} style="width:auto"></td><td><a href="#/chat/${s.user_id}">Message</a> · <a href="#/classroom/${s.course_id}">Discussion</a></td></tr>`))}`; };
views.earnings = async () => { const r = await call('earnings'); if (!r.ok) return `<p class="msg err">${esc(r.error)}</p>`; const k = (n, l) => `<div><b>${typeof n === 'number' && l !== 'Enrolments' ? rupee(n) : n}</b>${l}</div>`;
  return `<h2>Trainer earnings</h2><div class="kpi">${k(r.enrolments, 'Enrolments')}${k(r.gross, 'Gross revenue')}${k(r.refunds, 'Refunds')}${k(r.platform_fee, 'Platform fee (' + r.commission_pct + '%)')}${k(r.net, 'Net earnings')}${k(r.pending, 'Pending')}${k(r.in_process, 'Processing')}${k(r.paid_out, 'Paid')}</div><p class="card">${esc(r.formula)}</p><p class="meta">A payout counts as paid only after the admin records it. Payout details are handled outside this site.</p>${table(['Date', 'Amount', 'Status', 'Note'], r.payouts.map(p => `<tr><td>${date(p.created)}</td><td>${rupee(p.amount)}</td><td>${esc(p.status)}</td><td>${esc(p.note)}</td></tr>`))}`; };

// ---- admin extras ----
adminExtra.analytics = async () => { const a = await call('analytics', {scope: 'admin'}), t = a.totals || {}, k = (n, l) => `<div><b>${n ?? 0}</b>${l}</div>`;
  return `<div class="kpi">${k(t.users, 'Users')}${k(t.companies, 'Companies')}${k(t.verified, 'Verified')}${k(t.rfqs, 'RFQs')}${k(t.jobs, 'Jobs')}${k(t.courses, 'Courses')}${k(t.mro, 'MRO providers')}${k(t.subscriptions, 'Active subs')}${k(rupee(t.revenue || 0), 'Revenue')}</div>${chartsHtml(a.charts)}`; };
adminExtra.settings = async () => { const r = await call('settings_get'); if (!r.ok) return esc(r.error);
  return `<h3>Platform settings</h3><div class="kpi"><div><b>${esc(r.last_backup || 'never')}</b>Last backup</div><div><b>${r.email_quota}</b>Emails left today</div><div><b>${r.queued_mail}</b>Queued emails</div><div><b>${r.failed_mail}</b>Failed emails</div><div><b>${r.errors_24h}</b>Errors (24h)</div></div><p><button class="btn ghost sm" id="bkNow">Back up now</button></p>
  ${table(['Setting', 'Value', ''], r.data.map(s => `<tr><td><code>${esc(s.key)}</code></td><td><input data-setk="${esc(s.key)}" value="${esc(s.value)}"></td><td><button class="btn ghost sm" data-setsave="${esc(s.key)}">Save</button></td></tr>`))}<p class="meta">Keys such as Razorpay secrets are never stored here; they live in Apps Script “Script properties”.</p>`; };
adminExtra.templates = async () => { const r = await call('templates_get'); return `<h3>Email templates</h3><p class="meta">Use {{name}}, {{code}}, {{support_email}}, {{whatsapp}} and the placeholders shown in each template.</p>${(r.data || []).map(t => `<div class="card" style="margin-bottom:10px"><strong>${esc(t.key)}</strong><input data-tsub="${esc(t.key)}" value="${esc(t.subject)}"><textarea rows="5" data-tbody="${esc(t.key)}">${esc(t.body)}</textarea><button class="btn ghost sm" data-tsave="${esc(t.key)}">Save template</button></div>`).join('')}`; };
adminExtra.files = async () => { const r = await call('admin_list', {sheet: 'Files'}); return `<h3>Uploaded files</h3><p class="meta">Files stay private until marked clean (setting require_scan_for_sharing). Review a file in Google Drive (folder IA_Private_Files) before marking it clean; there is no automatic malware scanner here.</p>${table(['Date', 'Name', 'Size', 'Status', ''], (r.data || []).map(f => `<tr><td>${date(f.created)}</td><td>${esc(f.name)}</td><td>${Math.round(f.size / 1024)} KB</td><td>${esc(f.scan_status)}</td><td><button class="btn ghost sm" data-fscan="${f.id}|clean">Mark clean</button> <button class="btn ghost sm" data-fscan="${f.id}|quarantined">Quarantine</button></td></tr>`))}`; };
adminExtra.payouts = async () => { const r = await call('admin_list', {sheet: 'Payouts'}); return `<h3>Trainer payouts</h3>${table(['Date', 'Trainer ID', 'Amount', 'Status', ''], (r.data || []).map(p => `<tr><td>${date(p.created)}</td><td>${esc(p.trainer_id)}</td><td>${rupee(p.amount)}</td><td>${esc(p.status)}</td><td><select data-payout="${p.id}">${['Pending','Eligible','Processing','Paid','Failed','On Hold'].map(s => `<option ${s === p.status ? 'selected' : ''}>${s}</option>`).join('')}</select></td></tr>`))}<h4>Create payout record</h4>${form('payout_create', fld('trainer_id', 'Trainer user ID', {req: 1}) + fld('amount', 'Amount (₹)', {req: 1}) + fld('note', 'Note'), 'Create')}`; };
adminExtra.merge = async () => { const r = await call('admin_list', {sheet: 'Companies'}), cs = (r.data || []).filter(c => c.status !== 'Merged'); window._mergeCos = cs;
  const norm = s => String(s || '').toLowerCase().replace(/\b(pvt|private|ltd|limited|llp|inc)\b/g, '').replace(/[^a-z0-9]/g, ''), host = s => String(s || '').toLowerCase().replace(/^https?:\/\/(www\.)?/, '').split('/')[0], g = {};
  cs.forEach(c => [norm(c.name), host(c.website), String(c.email).toLowerCase()].filter(k => k && k.length > 3).forEach(k => (g[k] = g[k] || []).push(c))); const pairs = []; Object.values(g).forEach(a => { for (let i = 1; i < a.length; i++) if (!pairs.some(p => p[0].id === a[0].id && p[1].id === a[i].id)) pairs.push([a[0], a[i]]); });
  const opt = cs.map(c => `<option value="${c.id}">${esc(c.name)} (${esc(c.city || '—')}) ${esc(c.id)}</option>`).join('');
  return `<h3>Merge companies</h3><p class="meta">Populated fields in the existing record are never overwritten. Empty fields are filled from the duplicate. Differences become conflicts you decide. Nothing changes until you confirm.</p>
  ${pairs.length ? `<h4>Possible duplicates found (${pairs.length})</h4>${table(['Existing', 'Duplicate', ''], pairs.slice(0, 30).map(p => `<tr><td>${esc(p[0].name)}</td><td>${esc(p[1].name)}</td><td><button class="btn ghost sm" data-mpair="${p[0].id}|${p[1].id}">Compare</button></td></tr>`))}` : '<p class="empty">No likely duplicates detected.</p>'}
  <div class="two"><label>Existing record (kept)<select id="mEx">${opt}</select></label><label>Duplicate record (merged into existing)<select id="mDu">${opt}</select></label></div><button class="btn primary" id="mPrev">Compare &amp; preview</button><div id="mOut"></div>`; };
async function mergePreview() {
  const ex = $('#mEx').value, du = $('#mDu').value, choices = {}; document.querySelectorAll('[data-mc]:checked').forEach(x => choices[x.dataset.mc] = x.value);
  const r = await call('merge_preview', {existing_id: ex, duplicate_id: du, choices}); if (!r.ok) { $('#mOut').innerHTML = `<p class="msg err">${esc(r.error)}</p>`; return; }
  const E = window._mergeCos.find(c => c.id === ex), D = window._mergeCos.find(c => c.id === du), F = ['name','website','email','phone','country','state','city','address','industry','capabilities','certifications','description','products','services','materials'];
  const cf = f => r.conflicts.find(c => c.field === f), chg = f => r.changes.find(c => c.field === f);
  $('#mOut').innerHTML = `<h4>Side by side</h4>${table(['Field', 'Existing', 'Duplicate', 'Result'], F.map(f => { const c = cf(f), x = chg(f); return `<tr><td>${f}</td><td>${esc(E[f])}</td><td>${esc(D[f])}</td><td>${c ? `<strong>Conflict</strong><br><label><input type="radio" name="mc_${f}" data-mc="${f}" value="existing" ${c.resolved ? 'checked' : ''}> keep existing</label><br><label><input type="radio" name="mc_${f}" data-mc="${f}" value="duplicate" ${r.changes.some(z => z.field === f) ? 'checked' : ''}> use duplicate</label>` : x ? `<strong>${esc(x.from || 'EMPTY')} → ${esc(x.to)}</strong>` : E[f] ? 'Existing value retained' : '—'}</td></tr>`; }))}
  <h4>Merge preview — final record changes</h4>${r.changes.length ? `<ul>${r.changes.map(c => `<li>${esc(c.field)}: ${esc(c.from || 'EMPTY')} → <strong>${esc(c.to)}</strong> (${esc(c.why)})</li>`).join('')}</ul>` : '<p>No fields will change.</p>'}${r.needsDecision ? '<p class="msg err">Choose keep-existing or use-duplicate for every conflict, then press Preview again.</p><button class="btn ghost" id="mPrev2">Update preview</button>' : '<button class="btn primary" id="mGo">CONFIRM MERGE</button>'}<p class="msg" id="mMsg"></p>`;
  const again = $('#mPrev2'); if (again) again.onclick = mergePreview; const go = $('#mGo');
  if (go) go.onclick = async () => { if (!confirm('Merge the duplicate into the existing company? You can undo it from the Merges tab.')) return; const m = await call('merge_confirm', {existing_id: ex, duplicate_id: du, choices}); $('#mMsg').className = 'msg ' + (m.ok ? 'good' : 'err'); $('#mMsg').innerHTML = m.ok ? `Merged. Merge ID ${esc(m.merge_id)} (undo available in the Merges tab).` : esc(m.error); };
}

// ---- delegated handlers for the screens above ----
document.addEventListener('click', async e => { const t = e.target.closest('button, [data-mpair]'); if (!t) return; const d = t.dataset;
  if (t.id === 'acceptInv') { const r = await call('team_accept', {invite: sessionStorage.getItem('ia_invite')}); if (r.ok) { sessionStorage.removeItem('ia_invite'); const m = await call("me"); me = m.user; nav(); } alert(r.ok ? 'You have joined the company.' : r.error); route(); }
  if (d.trem && confirm('Remove this member?')) { await call('team_remove', {user_id: d.trem}); route(); } if (d.icancel) { await call('invite_cancel', {id: d.icancel}); route(); }
  if (t.id === 'gdisc') { const r = await call('google_disconnect'); alert(r.ok ? 'Google disconnected.' : r.error); route(); } if (t.id === 'delReq' && confirm('Request deletion of your account and data?')) { const r = await call('account_delete'); alert(r.message || r.error); }
  if (t.id === 'bkNow') { const r = await call('backup_now'); alert(r.ok ? 'Backup done: ' + r.last_backup : r.error); route(); }
  if (d.setsave) { const r = await call('settings_set', {key: d.setsave, value: document.querySelector(`[data-setk="${d.setsave}"]`).value}); alert(r.ok ? 'Saved.' : r.error); }
  if (d.tsave) { const r = await call('templates_set', {key: d.tsave, subject: document.querySelector(`[data-tsub="${d.tsave}"]`).value, body: document.querySelector(`[data-tbody="${d.tsave}"]`).value}); alert(r.ok ? 'Template saved.' : r.error); }
  if (d.fscan) { const [id, status] = d.fscan.split('|'); await call('file_scan_set', {id, status}); route(); }
  if (d.mpair) { const [a, b] = d.mpair.split('|'); $('#mEx').value = a; $('#mDu').value = b; mergePreview(); } if (t.id === 'mPrev') mergePreview();
  if (d.merges) { /* reserved */ } });
document.addEventListener('change', async e => { const t = e.target, d = t.dataset;
  if (d.trole) { const r = await call('team_role', {user_id: d.trole, role: t.value}); if (!r.ok) alert(r.error); route(); }
  if (d.lead) { const r = await call('lead_update', {id: d.lead, [d.f]: t.value}); if (!r.ok) alert(r.error); }
  if (d.app) { await call('application_status', {id: d.app, status: t.value}); } if (d.payout) { await call('payout_set', {id: d.payout, status: t.value}); }
  if (d.prog) { await call('enrol_update', {id: d.prog, progress: t.value}); } if (d.cert) { await call('enrol_update', {id: d.cert, certificate: t.checked}); } });




