const {describe, it, before} = require('node:test'), assert = require('node:assert/strict'), crypto = require('crypto'), {createEnv} = require('./mock');
const rzp = {captured: true, amountPaise: null, order: null};
const env = createEnv({props: {RZP_KEY_ID: 'rzp_test_x', RZP_KEY_SECRET: 'sekret'}, fetch: (url, o) => {
  if (url.includes('/orders')) { const b = JSON.parse(o.payload); rzp.order = {id: 'order_' + b.receipt, amount: b.amount}; return {code: 200, text: JSON.stringify(rzp.order)}; }
  if (url.includes('/payments/')) return {code: 200, text: JSON.stringify({order_id: rzp.order.id, currency: 'INR', amount: rzp.amountPaise ?? rzp.order.amount, status: rzp.status || 'captured'})};
  if (url.includes('tokeninfo')) { const t = decodeURIComponent(url.split('id_token=')[1]); return t.startsWith('good:') ? {code: 200, text: JSON.stringify({aud: 'client-123', email_verified: 'true', email: t.split(':')[1], sub: 'sub-' + t.split(':')[1], name: 'G User'})} : {code: 401, text: '{}'}; }
  return {code: 404, text: '{}'}; }});
env.set_('Settings', 'dev_show_codes', {value: 'TRUE'}, 'key'); env.set_('Settings', 'google_client_id', {value: 'client-123'}, 'key');
let n = 0; const P = (t, a, b) => env.post(t, a, b);
function mkUser(role = 'buyer', tag = 'u') { const email = `${tag}${++n}@t.example`, r = P(null, 'register', {name: 'Test ' + tag, email, password: 'Passw0rd!x', role}); assert.ok(r.ok && r.dev_code, JSON.stringify(r)); const v = P(null, 'verify', {email, code: r.dev_code}); assert.ok(v.ok, JSON.stringify(v)); return {token: v.token, id: v.user.id, email, call: (a, b) => P(v.token, a, b)}; }
const row = (sheet, f) => env.all_(sheet).find(f);
function adminize(u) { env.set_('Users', u.id, {roles: 'admin'}); }

describe('setup & public API', () => {
  it('creates all sheets, plans, templates, settings; is idempotent', () => { const rows = env.all_('Plans').length; env.setup(); assert.equal(env.all_('Plans').length, rows); assert.ok(Object.keys(env.sheets).length >= 30); assert.equal(env.get({action: 'settings'}).data.support_email, 'info@buye.online'); assert.ok(env.all_('Templates').length >= 8); assert.equal(env.get({action: 'plans'}).data.length, 4); });
  it('existing company rows survive setup and the public list hides unapproved/merged', () => { env.add_('Companies', {name: 'Old Co', status: 'Approved', city: 'Pune', email: 'private@old.example', phone: '123'}); env.add_('Companies', {name: 'Hidden', status: 'Pending'}); env.setup(); const r = env.get({action: 'companies'}); assert.ok(r.data.some(c => c.name === 'Old Co')); assert.ok(!r.data.some(c => c.name === 'Hidden')); assert.equal(r.data[0].email, undefined); assert.equal(r.data[0].phone, undefined); });
  it('unknown / inherited action names are rejected', () => { assert.equal(P(null, 'constructor').ok, false); assert.equal(P(null, 'toString').ok, false); assert.equal(P(null, 'nope').error, 'Unknown action'); });
});

describe('authentication', () => {
  it('register → verify → me → logout → me', () => {
    const email = 'flow@t.example', r = P(null, 'register', {name: 'Flow User', email, password: 'Passw0rd!x', role: 'supplier'}); assert.ok(/^\d{6}$/.test(r.dev_code));
    assert.match(P(null, 'login', {email, password: 'Passw0rd!x'}).error, /Verify your email/); assert.equal(P(null, 'verify', {email, code: '000000'}).ok, false);
    const v = P(null, 'verify', {email, code: env.all_('Outbox').length ? r.dev_code : r.dev_code}); assert.ok(v.ok && v.token); assert.equal(P(null, 'verify', {email, code: r.dev_code}).ok, false, 'used code');
    assert.equal(P(v.token, 'me').user.email, email); assert.equal(JSON.stringify(P(v.token, 'me')).includes('hash'), false); P(v.token, 'logout'); assert.equal(P(v.token, 'me').auth, true);
    assert.ok(P(null, 'login', {email, password: 'Passw0rd!x'}).ok); });
  it('hashes passwords, validates input, never stores plaintext', () => { assert.equal(P(null, 'register', {name: 'A', email: 'bad', password: 'x', role: 'buyer'}).ok, false); assert.match(P(null, 'register', {name: 'Weak', email: 'w@t.example', password: 'abcdefgh', role: 'buyer'}).error, /Password/); assert.equal(P(null, 'register', {name: 'Bad', email: 'b@t.example', password: 'Passw0rd!x', role: 'admin'}).error, 'Invalid account type');
    mkUser('buyer', 'hs'); assert.ok(env.all_('Users').every(u => !String(u.hash).includes('Passw0rd') && u.hash.length > 20)); });
  it('verification email is sent from the configured sender and uses the editable template', () => { const mails = env.mails.filter(m => /verification code/i.test(m.subject)); assert.ok(mails.length > 0); assert.equal(mails[0].from, 'info@buye.online'); assert.equal(mails[0].name, 'Indian Aeronautics'); assert.match(mails[0].body, /info@buye\.online/); });
  it('duplicate registration reveals nothing and creates no second account', () => { const u = mkUser('buyer', 'dup'), r = P(null, 'register', {name: 'Dup Again', email: u.email, password: 'Another1pass', role: 'buyer'}); assert.ok(r.ok); assert.equal(r.dev_code, undefined); assert.equal(env.all_('Users').filter(x => x.email === u.email).length, 1); });
  it('rate-limits wrong codes and wrong passwords', () => { const email = 'lim@t.example'; P(null, 'register', {name: 'Lim User', email, password: 'Passw0rd!x', role: 'buyer'}); let last; for (let i = 0; i < 8; i++) last = P(null, 'verify', {email, code: '111111'}); assert.match(last.error, /Too many/); });
  it('reset password invalidates sessions', () => { const u = mkUser('buyer', 'rs'), f = P(null, 'forgot', {email: u.email}); assert.ok(f.dev_code); assert.equal(P(null, 'reset', {email: u.email, code: f.dev_code, password: 'NewPassw0rd1'}).ok, true); assert.equal(u.call('me').auth, true); assert.ok(P(null, 'login', {email: u.email, password: 'NewPassw0rd1'}).ok); assert.equal(P(null, 'forgot', {email: 'ghost@t.example'}).ok, true); });
  it('Google: creates account, links to verified account, rejects bad token/audience, no duplicates', () => {
    const g = P(null, 'google_login', {credential: 'good:newg@t.example'}); assert.ok(g.ok && g.token); assert.equal(P(null, 'google_login', {credential: 'good:newg@t.example'}).user.id, g.user.id); assert.equal(env.all_('Users').filter(u => u.email === 'newg@t.example').length, 1);
    const pw = mkUser('supplier', 'link'); const l = P(null, 'google_login', {credential: 'good:' + pw.email}); assert.equal(l.user.id, pw.id, 'linked, not duplicated'); assert.equal(env.all_('Users').filter(u => u.email === pw.email).length, 1);
    assert.equal(P(null, 'google_login', {credential: 'bad'}).ok, false); const un = 'unv@t.example'; P(null, 'register', {name: 'Unv User', email: un, password: 'Passw0rd!x', role: 'buyer'}); assert.equal(P(null, 'google_login', {credential: 'good:' + un}).ok, false, 'unverified account is not hijacked by Google');
    assert.equal(P(l.token, 'google_disconnect').ok, true); });
  it('multiple roles on one account', () => { const u = mkUser('supplier', 'mr'); const r = u.call('roles_add', {role: 'buyer'}); assert.deepEqual(r.user.roles, ['supplier', 'buyer']); assert.equal(u.call('roles_add', {role: 'admin'}).ok, false); });
  it('protected actions need login; admin actions need admin', () => { assert.equal(P(null, 'dashboard').auth, true); const u = mkUser(); assert.equal(u.call('admin_list', {sheet: 'Users'}).error, 'Admin only'); assert.equal(u.call('settings_set', {key: 'support_email', value: 'x@y.z'}).error, 'Admin only'); });
});

describe('companies, claims, team permissions', () => {
  let owner, co, hr, proc, sales, other, nobody;
  before(() => { owner = mkUser('supplier', 'own'); other = mkUser('supplier', 'oth'); nobody = mkUser('buyer', 'nb'); co = owner.call('company_save', {name: 'ABC Aerospace', city: 'Chennai', industry: 'Aerospace Manufacturing', capabilities: '5-axis CNC machining, aluminium', email: 'info@abc.example', phone: '+91 9999999999'}).id; env.set_('Companies', co, {status: 'Approved'}); });
  it('owner manages company; dashboard shows completion', () => { assert.equal(owner.call('company_get').company.name, 'ABC Aerospace'); const d = owner.call('dashboard'); assert.ok(d.company.completion > 0); assert.equal(d.company_role, 'owner'); });
  it('public view never exposes private contact fields', () => { const c = env.get({action: 'companies'}).data.find(x => x.id === co); assert.ok(c); assert.equal(c.email, undefined); assert.equal(c.phone, undefined); assert.equal(c.address, undefined); });
  it('company claim: submit → admin approves → claimant manages', () => { const claimant = mkUser('company_rep', 'clm'), a = mkUser(); adminize(a); const target = env.add_('Companies', {name: 'Claimable Pvt', status: 'Approved', email: 'x@claim.example'}).id; assert.equal(claimant.call('company_get').company, null); assert.ok(claimant.call('claim_submit', {company_id: target, designation: 'CEO', company_email: 'ceo@claim.example', phone: '+91 1'}).ok); assert.equal(claimant.call('claim_submit', {company_id: target, designation: 'CEO', company_email: 'ceo@claim.example', phone: '+91 1'}).ok, false);
    const c = row('Claims', r => r.company_id === target); assert.equal(claimant.call('claim_review', {id: c.id, decision: 'Approved'}).error, 'Admin only'); assert.ok(a.call('claim_review', {id: c.id, decision: 'Approved'}).ok); assert.equal(claimant.call('company_get').company.id, target); assert.ok(claimant.call('company_save', {description: 'Now managed'}).ok); assert.ok(env.all_('Notifications').some(x => x.user_id === claimant.id && /Claimed/.test(x.text))); });
  it('another user cannot modify the company', () => { assert.equal(other.call('company_get').company, null); other.call('company_save', {name: 'Mine'}); assert.equal(row('Companies', c => c.id === co).name, 'ABC Aerospace'); });
  it('team: invite → accept → role-limited access (HR vs procurement vs sales)', () => {
    hr = mkUser('employer', 'hr'); proc = mkUser('buyer', 'proc'); sales = mkUser('supplier', 'sal');
    for (const [u, role] of [[hr, 'hr'], [proc, 'procurement'], [sales, 'sales']]) { const i = owner.call('team_invite', {email: u.email, name: 'M', role}); assert.ok(i.dev_invite_token); assert.equal(other.call('team_accept', {invite: i.dev_invite_token}).ok, false, 'token is bound to the invited email'); assert.ok(u.call('team_accept', {invite: i.dev_invite_token}).ok); }
    assert.equal(nobody.call('team_invite', {email: 'x@t.example', role: 'sales'}).ok, false); assert.equal(hr.call('team_invite', {email: 'y@t.example', role: 'viewer'}).ok, false);
    assert.equal(hr.call('rfq_create', {title: 'HR cannot', quantity: '1'}).ok, false); assert.equal(hr.call('company_save', {city: 'X'}).ok, false); assert.ok(hr.call('job_post', {title: 'Quality Engineer', apply_email: 'hr@abc.example'}).ok);
    assert.ok(proc.call('rfq_create', {title: 'Procurement RFQ', quantity: '10', visibility: 'Private'}).ok); assert.equal(proc.call('job_post', {title: 'Nope', apply_email: 'a@b.example'}).ok, false); assert.equal(proc.call('leads_list').ok, false);
    assert.ok(sales.call('leads_list').ok); assert.equal(sales.call('jobs_mine').ok, false); assert.equal(hr.call('leads_list').ok, false); assert.equal(hr.call('team_list').data.length, 4); });
  it('team members share the company; owner cannot be removed; roles can change', () => { const ms = owner.call('team_list').data, me = ms.find(m => m.role === 'owner'), h = ms.find(m => m.role === 'hr'); assert.equal(owner.call('team_remove', {user_id: me.id}).ok, false); assert.ok(owner.call('team_role', {user_id: h.id, role: 'viewer'}).ok); assert.equal(hr.call('job_post', {title: 'Z', apply_email: 'a@b.example'}).ok, false); assert.ok(owner.call('team_role', {user_id: h.id, role: 'hr'}).ok); });
  it('leads: enquiry creates lead; sales updates status; invalid status refused', () => { const e = P(null, 'enquiry', {company_id: co, buyer_name: 'Buyer', buyer_email: 'b@buyer.example', requirement: 'Need 500 brackets'}); assert.ok(e.ok); assert.equal(P(null, 'enquiry', {company_id: 'nope', buyer_name: 'B', buyer_email: 'b@buyer.example', requirement: 'x'}).ok, false);
    const l = sales.call('leads_list').data[0]; assert.ok(sales.call('lead_update', {id: l.id, status: 'Qualified', est_value: '50000'}).ok); assert.equal(sales.call('lead_update', {id: l.id, status: 'Bogus'}).ok, false); assert.equal(nobody.call('leads_list').ok, false); });
  it('jobs: HR posts → admin approves → professional applies → HR sees applicant (no email exposed)', () => { const a = mkUser(); adminize(a); const j = hr.call('jobs_mine').data[0]; a.call('admin_set', {sheet: 'Jobs', id: j.id, patch: {status: 'Approved'}}); const pro = mkUser('professional', 'pro'); assert.ok(env.get({action: 'jobs'}).data.some(x => x.id === j.id)); assert.ok(pro.call('job_apply', {job_id: j.id, message: 'Keen'}).ok); assert.equal(pro.call('job_apply', {job_id: j.id}).ok, false);
    const apps = hr.call('applications', {job_id: j.id}).data; assert.equal(apps.length, 1); assert.equal(JSON.stringify(apps).includes(pro.email), false); assert.equal(proc.call('applications', {job_id: j.id}).ok, false); hr.call('application_status', {id: apps[0].id, status: 'Shortlisted'}); assert.ok(env.all_('Notifications').some(x => x.user_id === pro.id && /Shortlisted/.test(x.text))); });
});

describe('merge, import, export', () => {
  let a;
  before(() => { a = mkUser(); adminize(a); });
  it('spec merge test: existing populated fields kept, empty phone filled, conflict needs a decision, undo restores', () => {
    const ex = env.add_('Companies', {name: 'ABC Aerospace', email: 'info@abc.com', phone: '', website: 'abc.com', city: 'Chennai', status: 'Approved'}).id, du = env.add_('Companies', {name: 'ABC Aerospace Pvt Ltd', email: '', phone: '+91 9999999999', website: 'abc.com', city: '', status: 'Approved'}).id;
    const pv = a.call('merge_preview', {existing_id: ex, duplicate_id: du}); assert.deepEqual(pv.changes.map(c => c.field), ['phone']); assert.ok(pv.conflicts.some(c => c.field === 'name') && pv.needsDecision); assert.equal(a.call('merge_confirm', {existing_id: ex, duplicate_id: du}).ok, false);
    assert.equal(mkUser().call('merge_preview', {existing_id: ex, duplicate_id: du}).error, 'Admin only'); const cf = a.call('merge_confirm', {existing_id: ex, duplicate_id: du, choices: {name: 'existing'}}); assert.ok(cf.ok);
    const r = row('Companies', c => c.id === ex); assert.equal(r.name, 'ABC Aerospace'); assert.equal(r.email, 'info@abc.com'); assert.equal(r.phone, '+91 9999999999'); assert.equal(r.website, 'abc.com'); assert.equal(r.city, 'Chennai'); assert.equal(row('Companies', c => c.id === du).status, 'Merged');
    assert.ok(env.all_('Audit').some(x => x.action === 'company_merge')); assert.equal(JSON.parse(row('Merges', m => m.id === cf.merge_id).previous).phone, ''); assert.ok(a.call('merge_undo', {merge_id: cf.merge_id}).ok); assert.equal(String(row('Companies', c => c.id === ex).phone), ''); assert.equal(row('Companies', c => c.id === du).status, 'Pending'); assert.equal(a.call('merge_undo', {merge_id: cf.merge_id}).ok, false); });
  it('conflict resolution: admin picks duplicate value', () => { const ex = env.add_('Companies', {name: 'C1', city: 'Chennai', status: 'Approved'}).id, du = env.add_('Companies', {name: 'C1', city: 'Bengaluru', status: 'Approved'}).id; a.call('merge_confirm', {existing_id: ex, duplicate_id: du, choices: {city: 'duplicate'}}); assert.equal(row('Companies', c => c.id === ex).city, 'Bengaluru'); });
  it('import: validates, flags duplicates, merges only empties, records history', () => {
    const rows = [{name: 'Fresh Aero Ltd', email: 'hello@fresh.example', website: 'fresh.example', city: 'Hosur'}, {name: 'Bad Email Co', email: 'nope'}, {name: 'Old Co', email: 'private@old.example', phone: '', city: 'Pune', capabilities: 'Welding'}, {name: 'No Name', email: 'a@b.example', website: 'not a url'}];
    const chk = a.call('import_check', {rows}).data; assert.equal(chk[0].errors.length, 0); assert.ok(chk[1].errors.includes('Invalid email')); assert.ok(chk[2].dup && chk[2].dup.name === 'Old Co'); assert.ok(chk[3].errors.includes('Invalid URL'));
    const r = a.call('import_commit', {rows: rows.map((x, i) => ({row: x, decision: i === 2 ? 'merge' : 'create'})), publish: true, file: 'test.xlsx'}); assert.deepEqual([r.made, r.merged, r.skipped, r.errors], [1, 1, 2, 2]); const old = row('Companies', c => c.name === 'Old Co'); assert.equal(old.city, 'Pune'); assert.equal(old.capabilities, 'Welding'); assert.equal(old.email, 'private@old.example');
    assert.equal(env.all_('Companies').filter(c => c.name === 'Fresh Aero Ltd')[0].status, 'Approved'); assert.equal(env.all_('Imports').length, 1); assert.equal(a.call('import_commit', {rows: [{row: rows[0]}]}).made, 0, 're-import without an explicit decision never creates a duplicate'); assert.equal(a.call('import_commit', {rows: [{row: rows[0], decision: 'create'}]}).made, 1, 'admin may explicitly create a separate record'); });
  it('export strips secrets and requires admin', () => { const x = a.call('export_data', {kind: 'users'}); assert.ok(x.header.indexOf('hash') < 0 && x.header.indexOf('salt') < 0 && x.header.indexOf('code') < 0); assert.ok(x.rows.length > 0); assert.equal(mkUser().call('export_data', {kind: 'users'}).error, 'Admin only'); for (const k of ['companies', 'verified', 'suppliers', 'mro', 'training', 'rfqs', 'leads']) assert.ok(a.call('export_data', {kind: k}).ok, k); });
});

describe('RFQ, quotations, files, messaging', () => {
  let buyer, sup, supCo, a, pub, priv, ver, fid;
  before(() => { buyer = mkUser('buyer', 'by'); sup = mkUser('supplier', 'sp'); a = mkUser(); adminize(a); supCo = sup.call('company_save', {name: 'Precision Parts', city: 'Bengaluru', capabilities: '5-axis CNC machining, aluminium', industry: 'Aerospace Manufacturing'}).id; env.set_('Companies', supCo, {status: 'Approved'}); });
  it('visibility rules decide what a supplier sees', () => { const mk = (t, v) => buyer.call('rfq_create', {title: t, quantity: '100', material: 'Aluminium', process: '5-axis CNC', visibility: v, certification: 'Required'});
    pub = mk('Public 5-axis CNC bracket', 'Public'); priv = mk('Private bracket', 'Private'); ver = mk('Verified bracket', 'Verified suppliers'); assert.match(pub.rfq_no, /^RFQ-IA-\d{6}$/); assert.ok(pub.matched >= 1);
    let feed = sup.call('rfq_feed').data.map(r => r.id); assert.ok(feed.includes(pub.id) && !feed.includes(priv.id) && !feed.includes(ver.id)); assert.equal(sup.call('rfq_get', {id: priv.id}).ok, false); assert.equal(sup.call('rfq_get', {id: ver.id}).ok, false);
    env.set_('Companies', supCo, {verification: 'Profile Verified'}); feed = sup.call('rfq_feed').data.map(r => r.id); assert.ok(feed.includes(ver.id)); assert.ok(sup.call('rfq_get', {id: ver.id}).ok); assert.equal(buyer.call('rfq_mine').data.length, 3); });
  it('matching notifies the supplier and explains why; no invented data', () => { assert.ok(env.all_('Notifications').some(n => n.user_id === sup.id && /matching your capabilities/.test(n.text))); const m = buyer.call('rfq_match', {id: pub.id}); assert.equal(m.ai, true); assert.ok(m.matches[0].why.length > 0); assert.ok(m.matches[0].notes.some(x => /Certification information not available/.test(x))); assert.equal(sup.call('rfq_match', {id: pub.id}).ok, false); });
  it('private file: upload validated, owner-only until reviewed, then RFQ-scoped; strangers never', () => {
    const pdf = Buffer.from('%PDF-1.4 drawing'), up = buyer.call('upload', {name: 'drawing.pdf', data: pdf.toString('base64')}); assert.ok(up.ok); fid = up.id; assert.equal(up.scan_status, 'unscanned'); const f = row('Files', x => x.id === fid); assert.equal(env.drive.files[f.drive_id].sharing[0], 'PRIVATE');
    assert.equal(buyer.call('upload', {name: 'evil.exe', data: pdf.toString('base64')}).error, 'File type not allowed'); assert.equal(buyer.call('upload', {name: 'fake.pdf', data: Buffer.from('MZ not a pdf').toString('base64')}).error, 'File content does not match its type'); assert.equal(buyer.call('upload', {name: 'big.pdf', data: Buffer.concat([pdf, Buffer.alloc(6 * 1048576)]).toString('base64')}).error, 'File too large (max 5 MB)');
    assert.ok(buyer.call('download', {id: fid}).ok); env.set_('RFQs', pub.id, {file_ids: fid}); assert.equal(sup.call('download', {id: fid}).error, 'File verification pending', 'unscanned files are not shared');
    assert.ok(a.call('file_scan_set', {id: fid, status: 'clean'}).ok); assert.ok(sup.call('download', {id: fid}).ok); const stranger = mkUser('buyer', 'st'); assert.equal(stranger.call('download', {id: fid}).ok, false); env.set_('RFQs', pub.id, {visibility: 'Private'}); assert.equal(sup.call('download', {id: fid}).ok, false, 'access follows RFQ visibility'); env.set_('RFQs', pub.id, {visibility: 'Public'});
    a.call('file_scan_set', {id: fid, status: 'quarantined'}); assert.equal(sup.call('download', {id: fid}).ok, false); assert.equal(env.drive.files[f.drive_id].trashed, true); assert.ok(buyer.call('files_mine').data.length >= 1); });
  it('quotation needs the plan; Razorpay payment verified server-side; replay/tamper rejected', () => {
    assert.match(sup.call('quote_submit', {rfq_id: pub.id, price: 500, lead_time: '30 days'}).error, /plan does not include/);
    const o = sup.call('checkout', {plan_id: 'professional'}); assert.equal(o.amount, 5898.82); assert.equal(o.key_id, 'rzp_test_x'); const pay = 'pay_1', sig = crypto.createHmac('sha256', 'sekret').update(o.order_id + '|' + pay).digest('hex');
    assert.match(sup.call('payment_verify', {order_id: o.order_id, payment_id: pay, signature: 'forged'}).error, /could not be verified/); assert.equal(sup.call('me').plan.id, 'free');
    rzp.amountPaise = 100; assert.equal(sup.call('payment_verify', {order_id: o.order_id, payment_id: pay, signature: sig}).ok, false, 'amount mismatch'); rzp.amountPaise = null; assert.equal(sup.call('me').plan.id, 'free');
    const ok = sup.call('payment_verify', {order_id: o.order_id, payment_id: pay, signature: sig}); assert.equal(ok.status, 'Paid'); assert.equal(sup.call('me').plan.id, 'professional'); assert.equal(sup.call('payment_verify', {order_id: o.order_id, payment_id: pay, signature: sig}).status, 'Paid');
    assert.equal(env.all_('Subscriptions').filter(s => s.user_id === sup.id && s.status === 'Active').length, 1, 'idempotent'); const p = sup.call('payments_mine').data[0]; assert.match(p.invoice_no, /^INV-IA-/); assert.equal(buyer.call('payments_mine').data.length, 0);
    const o2 = sup.call('checkout', {plan_id: 'business'}); assert.equal(sup.call('payment_verify', {order_id: o2.order_id, payment_id: pay, signature: crypto.createHmac('sha256', 'sekret').update(o2.order_id + '|' + pay).digest('hex')}).ok, false, 'payment id cannot be replayed on another order'); assert.ok(env.mails.some(m => /Payment confirmed/.test(m.subject))); });
  it('payment links (no gateway keys): manual admin confirmation activates the plan', () => { const e2 = createEnv(); e2.set_('Plans', 'professional', {payment_link: 'https://rzp.io/l/test'}); const u = (() => { const em = 'pl@t.example', r = e2.post(null, 'register', {name: 'Link Payer', email: em, password: 'Passw0rd!x', role: 'supplier'}); e2.set_('Settings', 'dev_show_codes', {value: 'TRUE'}, 'key'); const r2 = e2.post(null, 'resend', {email: em}); return e2.post(null, 'verify', {email: em, code: r2.dev_code}); })(); const c = e2.post(u.token, 'checkout', {plan_id: 'professional'}); assert.equal(c.link, 'https://rzp.io/l/test'); const pay = e2.all_('Payments')[0]; assert.equal(pay.status, 'Pending'); assert.equal(e2.post(u.token, 'payment_confirm', {id: pay.id}).error, 'Admin only'); assert.equal(e2.post(u.token, 'checkout', {plan_id: 'business'}).ok, false, 'no link, no keys: refuses'); });
  it('buyer reviews quotes; only the buyer changes status; no auto-"best"', () => {
    const q = sup.call('quote_submit', {rfq_id: pub.id, price: 500, currency: 'INR', lead_time: '30 days', moq: '50'}); assert.ok(q.ok); assert.equal(sup.call('quote_submit', {rfq_id: pub.id, price: -5, lead_time: 'x'}).ok, false); const v = buyer.call('rfq_get', {id: pub.id}); assert.equal(v.quotes.length, 1); assert.equal(v.rfq.status, 'Responses Received');
    const qid = v.quotes[0].id; assert.equal(sup.call('quote_status', {id: qid, status: 'Preferred'}).ok, false); assert.ok(buyer.call('quote_status', {id: qid, status: 'Shortlisted'}).ok); assert.equal(buyer.call('quote_status', {id: qid, status: 'Best'}).ok, false); assert.equal(sup.call('rfq_status', {id: pub.id, status: 'Closed'}).ok, false); assert.ok(buyer.call('rfq_status', {id: pub.id, status: 'Closed'}).ok);
    assert.ok(env.all_('Notifications').some(n => n.user_id === buyer.id && /quotation/i.test(n.text))); assert.equal(buyer.call('dashboard').rfqs.find(r => r.id === pub.id).responses, 1); assert.equal(sup.call('rfq_get', {id: pub.id}).quotes.length, 1); });
  it('messaging: private threads, unread counts, block, report', () => { assert.ok(buyer.call('msg_send', {to_id: sup.id, body: 'Can you quote 500 units?'}).ok); const stranger = mkUser('buyer', 'ms'); assert.equal(sup.call('msg_inbox').unread, 1); assert.equal(stranger.call('msg_thread', {with: buyer.id}).data.length, 0); assert.equal(stranger.call('msg_inbox').data.length, 0);
    assert.equal(sup.call('msg_thread', {with: buyer.id}).data.length, 1); assert.equal(sup.call('msg_inbox').unread, 0); assert.equal(buyer.call('msg_send', {to_id: buyer.id, body: 'x'}).ok, false); assert.equal(buyer.call('msg_send', {to_id: sup.id, body: ''}).ok, false); sup.call('msg_block', {with: buyer.id}); assert.equal(buyer.call('msg_send', {to_id: sup.id, body: 'again'}).ok, false); assert.ok(sup.call('msg_report', {with: buyer.id, reason: 'spam'}).ok); assert.ok(env.all_('Tickets').some(t => t.subject === 'User report')); });
});

describe('academy, earnings, analytics, admin, contact, backup', () => {
  let tr, st, a, course;
  before(() => { tr = mkUser('trainer', 'tr'); st = mkUser('student', 'stu'); a = mkUser(); adminize(a); });
  it('trainer submits → admin approves → student enrols (paid course awaits payment)', () => { assert.equal(st.call('course_submit', {title: 'X', description: 'Y'}).ok, false); assert.ok(tr.call('course_submit', {title: 'CATIA Basics', description: 'Intro', price: '1000', category: 'Aerospace'}).ok); course = env.all_('Courses')[0].id; assert.equal(env.get({action: 'courses'}).data.length, 0); a.call('admin_set', {sheet: 'Courses', id: course, patch: {status: 'Approved'}}); assert.equal(env.get({action: 'courses'}).data.length, 1);
    assert.ok(st.call('enrol', {course_id: course}).ok); assert.equal(st.call('enrol', {course_id: course}).ok, false); const mine = st.call('my_courses').data[0]; assert.equal(mine.status, 'Awaiting payment'); assert.equal(st.call('discussion_post', {course_id: course, body: 'hi'}).ok, false, 'not active yet'); });
  it('earnings: ₹1,000 sale at 20% = ₹200 fee, ₹800 net; refunds recalculated; payouts tracked', () => { const e = env.all_('Enrolments')[0]; assert.equal(st.call('enrol_pay', {id: e.id}).error, 'Admin only'); assert.ok(a.call('enrol_pay', {id: e.id}).ok); let r = tr.call('earnings'); assert.deepEqual([r.gross, r.platform_fee, r.net, r.pending], [1000, 200, 800, 800]); assert.match(r.formula, /net 800/);
    a.call('settings_set', {key: 'commission_pct', value: '30'}); r = tr.call('earnings'); assert.equal(r.net, 700); a.call('settings_set', {key: 'commission_pct', value: '20'}); const po = a.call('payout_create', {trainer_id: tr.id, amount: 500}); assert.equal(tr.call('earnings').pending, 800); a.call('payout_set', {id: po.id, status: 'Paid'}); r = tr.call('earnings'); assert.deepEqual([r.paid_out, r.pending], [500, 300]); assert.equal(tr.call('payout_set', {id: po.id, status: 'Paid'}).error, 'Admin only');
    a.call('enrol_refund', {id: e.id}); r = tr.call('earnings'); assert.deepEqual([r.gross, r.refunds, r.net], [1000, 1000, 0]); a.call('enrol_pay', {id: e.id}); env.set_('Enrolments', e.id, {refunded: 0, status: 'Active'}); });
  it('student dashboard, progress, certificate, course discussion without contact details', () => { const e = env.all_('Enrolments')[0]; assert.ok(tr.call('enrol_update', {id: e.id, progress: 60, certificate: true}).ok); assert.equal(st.call('enrol_update', {id: e.id, progress: 100}).ok, false); const m = st.call('my_courses').data[0]; assert.deepEqual([m.progress, m.certificate, m.paid], [60, true, true]);
    assert.ok(tr.call('discussion_post', {course_id: course, kind: 'announcement', body: 'Welcome'}).ok); assert.ok(st.call('discussion_post', {course_id: course, body: 'Question?'}).ok); const d = st.call('discussion_list', {course_id: course}); assert.equal(d.data.length, 2); assert.equal(JSON.stringify(d).includes('@'), false); assert.equal(mkUser().call('discussion_list', {course_id: course}).ok, false); assert.ok(env.all_('Notifications').some(n => n.user_id === st.id && /Announcement/.test(n.text)));
    const students = tr.call('course_students'); assert.equal(students.data[0].student, st.call('me').user.name); assert.equal(JSON.stringify(students).includes(st.email), false); });
  it('analytics from real data only; empty => no charts; admin totals', () => { const fresh = mkUser('buyer', 'an'); assert.deepEqual(fresh.call('analytics').charts, []); const adm = a.call('analytics', {scope: 'admin'}); assert.ok(adm.charts.find(c => c.id === 'reg').values.length > 0); assert.ok(adm.totals.users > 10); assert.ok(adm.totals.revenue > 0); assert.equal(mkUser().call('analytics', {scope: 'admin'}).totals, undefined);
    const t = tr.call('analytics'); assert.ok(t.charts.some(c => c.id === 'enrol')); assert.ok(env.all_('Views').length === 0); P(null, 'view', {id: env.all_('Companies').find(c => c.status === 'Approved').id}); assert.equal(env.all_('Views')[0].count, 1); });
  it('admin: lists hide secrets; settings/templates editable; user suspend blocks login', () => { const l = a.call('admin_list', {sheet: 'Users'}); assert.ok(l.data.every(u => u.hash === undefined && u.salt === undefined && u.code === undefined)); assert.equal(a.call('admin_list', {sheet: 'Sessions'}).ok, false);
    assert.ok(a.call('settings_set', {key: 'support_email', value: 'help@buye.online'}).ok); assert.equal(env.get({action: 'settings'}).data.support_email, 'help@buye.online'); a.call('settings_set', {key: 'support_email', value: 'info@buye.online'}); assert.equal(a.call('settings_set', {key: 'google_client_secret', value: 'x'}).ok, false);
    assert.ok(a.call('templates_set', {key: 'email_verification', subject: 'Code: {{code}}', body: 'Hi {{name}} {{code}}'}).ok); const u = mkUser(); a.call('admin_set', {sheet: 'Users', id: u.id, patch: {status: 'Suspended'}}); assert.equal(u.call('me').auth, true); assert.match(P(null, 'login', {email: u.email, password: 'Passw0rd!x'}).error, /suspended/i); const s = a.call('settings_get'); assert.ok(s.email_quota > 0); });
  it('contact form: ticket + acknowledgement + spam protection', () => { const r = P(null, 'contact', {name: 'Visitor', email: 'v@visit.example', subject: 'Help', message: 'Need help registering my company'}); assert.ok(r.ok && r.ref); assert.ok(env.mails.some(m => m.to === 'v@visit.example' && /received/i.test(m.subject))); assert.ok(P(null, 'contact', {name: 'Bot', email: 'bot@x.example', subject: 's', message: 'm', website_url_hp: 'http://spam'}).ok); assert.equal(env.all_('Tickets').filter(t => t.email === 'bot@x.example').length, 0); for (let i = 0; i < 3; i++) P(null, 'contact', {name: 'V', email: 'flood@x.example', subject: 's', message: 'm'}); assert.match(P(null, 'contact', {name: 'V', email: 'flood@x.example', subject: 's', message: 'm'}).error, /Too many/); });
  it('mail queue: failures retry later and respect the daily quota; backup rotates', () => { const e2 = createEnv({mailFail: true}); e2.set_('Settings', 'dev_show_codes', {value: 'TRUE'}, 'key'); const r = e2.post(null, 'register', {name: 'Q User', email: 'q@t.example', password: 'Passw0rd!x', role: 'buyer'}); assert.ok(r.ok && r.dev_code); assert.equal(e2.all_('Outbox')[0].status, 'queued'); assert.equal(e2.all_('Outbox')[0].attempts, 1);
    const e3 = createEnv({quota: 0}); e3.post(null, 'register', {name: 'Q User', email: 'q@t.example', password: 'Passw0rd!x', role: 'buyer'}); assert.equal(e3.all_('Outbox')[0].status, 'queued'); assert.equal(e3.mails.length, 0); for (let i = 0; i < 3; i++) env.backup_(); assert.ok(env.all_('Settings').find(s => s.key === 'last_backup').value); assert.ok(Object.values(env.drive.files).filter(f => /^IA Backup/.test(f.name) && !f.trashed).length <= 8 && Object.values(env.drive.files).some(f => /^IA Backup/.test(f.name))); });
  it('unexpected errors are logged, never leaked to the user', () => { const r = JSON.parse(env.doPost({postData: {contents: '{not json'}}).text); assert.equal(r.ok, false); assert.match(r.error, /Something went wrong/); assert.ok(env.all_('Errors').length >= 1); assert.equal(r.error.includes('SyntaxError'), false); });
});
